baseURL = "http://sps-zone-1.github.io"
languageCode = "en-us"
title = "SPS Zone 1"
theme = "hugo-whisper-theme"

enableEmoji = true # use https://www.webfx.com/tools/emoji-cheat-sheet/
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Zone Meeting Spring 2022"
    url = "/zone-meeting-2022/"
    weight = 2

[[menu.main]]
    name = "Zone Meeting"
    url = "/zone-meeting/"
    weight = 2

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4


[params]
  mainSections = ["zone-meeting", "zone-meeting-2022", "resources", "contact"] #make sure to add new pages to the mainSections!!

  google_analytics_id=""
  homepage_button_link = '/zone-meeting-2022'
  homepage_button_text = 'Zone Meeting Sign-up and Information'
  homepage_intro = 'This is the Society of Physics Students Zone 1 site.'
  homepage_image = '/images/sps.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "This is the official website of the Society of Physics Students Zone 1."
    meta_og_title = "Society of Physics Students Zone 1"
    meta_og_type = "website"
    meta_og_url = "https://sps-zone-1.github.io"
    meta_og_image = '/images/sps.gif'
    meta_og_description = "This is the official website of the Society of Physics Students Zone 1."
    # meta_twitter_card = "summary"
    # meta_twitter_site = "@zerostaticio"
    # meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo.gif"
      standard  = "/images/logo.gif"
